// header file for main.cpp
#include <iostream>
#include <string>
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include <sstream>
#include <fstream>
#include <algorithm>
#include <iterator>
#include <ctime>
#include <cstdlib>
#include <ctime>
#include <cmath>
#include <iomanip>
#include <map>
#include <set>
#include <utility>
#include <functional>
#include <cctype>
#include <locale>
#include <numeric>
#include <stack>
#include <queue>
#include <list>
#include <deque>
#include <unistd.h>
#include <limits>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <unistd.h>
#include <QApplication>
#include <QLabel>
#include <QLineEdit>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QTextEdit>
#include <QTextStream>
#include <QFile>
#include <QTextStream>  
#include <QUrl>
#include <QPushButton>
#include <QCoreApplication>
#include <QFileDialog>
#include <QMessageBox>

#include <QWebEngineView>